import { RemoteKeyCode } from "androidtv-remote"

const KEYS: Record<string, number> = {
  home: RemoteKeyCode.KEYCODE_HOME,
  back: RemoteKeyCode.KEYCODE_BACK,
  power: RemoteKeyCode.KEYCODE_POWER,
  up: RemoteKeyCode.KEYCODE_DPAD_UP,
  down: RemoteKeyCode.KEYCODE_DPAD_DOWN,
  left: RemoteKeyCode.KEYCODE_DPAD_LEFT,
  right: RemoteKeyCode.KEYCODE_DPAD_RIGHT,
  select: RemoteKeyCode.KEYCODE_DPAD_CENTER,
  play: RemoteKeyCode.KEYCODE_MEDIA_PLAY_PAUSE,
  stop: RemoteKeyCode.KEYCODE_MEDIA_STOP,
  next: RemoteKeyCode.KEYCODE_MEDIA_NEXT,
  prev: RemoteKeyCode.KEYCODE_MEDIA_PREVIOUS,
  fwd: RemoteKeyCode.KEYCODE_MEDIA_FAST_FORWARD,
  rwd: RemoteKeyCode.KEYCODE_MEDIA_REWIND,
  "vol-up": RemoteKeyCode.KEYCODE_VOLUME_UP,
  "vol-down": RemoteKeyCode.KEYCODE_VOLUME_DOWN,
  mute: RemoteKeyCode.KEYCODE_VOLUME_MUTE,
  menu: RemoteKeyCode.KEYCODE_MENU,
  search: RemoteKeyCode.KEYCODE_SEARCH,
  sleep: RemoteKeyCode.KEYCODE_SLEEP,
  wakeup: RemoteKeyCode.KEYCODE_WAKEUP,
  input: RemoteKeyCode.KEYCODE_TV_INPUT,
  enter: RemoteKeyCode.KEYCODE_ENTER,
  "channel-up": RemoteKeyCode.KEYCODE_CHANNEL_UP,
  "channel-down": RemoteKeyCode.KEYCODE_CHANNEL_DOWN,
  info: RemoteKeyCode.KEYCODE_INFO,
  guide: RemoteKeyCode.KEYCODE_GUIDE,
  settings: RemoteKeyCode.KEYCODE_SETTINGS,
}

const KEY_LABELS: Record<string, string> = {
  home: "Home",
  back: "Back",
  power: "Power",
  up: "▲",
  down: "▼",
  left: "◄",
  right: "►",
  select: "OK",
  play: "⏯",
  stop: "⏹",
  next: "⏭",
  prev: "⏮",
  fwd: "⏩",
  rwd: "⏪",
  "vol-up": "Vol+",
  "vol-down": "Vol-",
  mute: "Mute",
  menu: "Menu",
  search: "Search",
}

export { KEYS, KEY_LABELS }
